### ISSUE TITLE
Missing gdnative source code

### ISSUE THREAD

**Issue by 3ddelano** [cybereality/godot-space-mouse#1]
Since the project is MIT licensed, it would be nice to have the source of the gdnative spacemouse.

**Comment by cybereality** [comment]
Yes, that is possible. I was focusing on getting the plugin out first, but I can also release the code for the library. That was the hard part actually, so it's probably more useful anyhow. It's too late tonight, but I can get it posted in the next day or so. Thanks.

**Comment by cybereality** [comment]
I was able to post the source code. Check the main page if you're interested. Thanks for asking about this.

**Comment by 3ddelano** [comment]
👍
