### ISSUE TITLE
Addon not working on Ubuntu 20.04.4 with Godot 3.5

### ISSUE THREAD

**Issue by kalbfled** [cybereality/godot-space-mouse#4]
I followed the installation instructions, including enabling the addon and copying the udev rules.  I see the "Space" UI panel, but there is no response to Space Mouse input.  It works as expected in Blender.

In the Space UI, I tried camera and object mode.  I tried unplugging and re-plugging the Space Mouse receiver, and I tried running the udevadm commands you specify.

**Comment by cybereality** [comment]
Which model Space Nav do you have? I just tested on Godot 3.5 and Ubuntu 22.04.1 and it still seems to be working. Are there any errors or warnings in the console? The plug-in also doesn't refresh when the editor is open, so if you replug it in, you have to restart the editor. I've noticed sometimes testing in Blender first, then opening Godot can help if it loses the connection.

**Comment by kalbfled** [comment]
Thank you for the timely response.  I have the [3dconnexion Space Mouse Wireless](https://3dconnexion.com/us/product/spacemouse-wireless/), which I purchased new about 3 or 4 years ago.

In the console (with non-system directory paths replaced by ellipses:
```
...$ OpenGL ES 2.0 Renderer: NVIDIA GeForce GTX 980/PCIe/SSE2
/lib/x86_64-linux-gnu/libasound.so.2: undefined symbol: snd_dlpath
 
ERROR: Can't open dynamic library: .../addons/spacemouse/bin/libspacemouse.so. Error: libhidapi-hidraw.so.0: cannot open shared object file: No such file or directory
   at: open_dynamic_library (drivers/unix/os_unix.cpp:412)
ERROR: No valid library handle, can't get symbol from GDNative object
   at: get_symbol (modules/gdnative/gdnative.cpp:510)
ERROR: No nativescript_init in "res://addons/spacemouse/bin/libspacemouse.so" found
   at: init_library (modules/gdnative/nativescript/nativescript.cpp:1503)
SCRIPT ERROR: Attempt to call function 'new' in base 'NativeScript' on a null instance.
          at: _ready (res://addons/spacemouse/SpaceMouse.gd:7)
```

I'm missing a dynamic link library.  I don't know if it matters, but I installed Godot by downloading the Linux binaries directly from the website and unzipping them.

**Comment by cybereality** [comment]
It looks like you have to do this:
`sudo apt install libhidapi-hidraw0`
I thought that came with Ubuntu, but I guess not. If that works, I'll update the README.

**Comment by cybereality** [comment]
You may also need to add this line to your `.profile`
`export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`

**Comment by kalbfled** [comment]
It works after installing libhidapi-hidraw0.  I didn't need the export line.  Thank you so much for this addon.  This functionality has been on my wish list since I started using Godot in 2019.
